name: DEPLOY

on:
  push:
    tags:
      - 'v*'

env:
  FORCED_VERSION: ${{ github.ref }}
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPEUSERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPEPASSWORD }}

jobs:
  publish-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: CALL gradlew.bat --no-daemon -DCI=true
        shell: cmd
      - run: CALL gradlew.bat --no-daemon jvmTest publishMingwX64PublicationToMavenRepository -DCI=true
        shell: cmd
        env:
          DISABLE_JAVASCRIPT_TEST: true
  publish-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew -DCI=true
      - run: ./gradlew jvmTest publishMacosX64PublicationToMavenRepository -DCI=true
        env:
          DISABLE_JAVASCRIPT_TEST: true
  publish-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew -DCI=true
      - run: ./gradlew publishIosArm64PublicationToMavenRepository publishIosX64PublicationToMavenRepository -DCI=true
        env:
          DISABLE_JAVASCRIPT_TEST: true
  publish-jvm-multiplatform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum ./gradlew --no-daemon -DCI=true
      - run: xvfb-run --auto-servernum ./gradlew --no-daemon publishKotlinMultiplatformPublicationToMavenRepository publishJvmPublicationToMavenRepository -DCI=true
  publish-js-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum ./gradlew --no-daemon -DCI=true
      - run: xvfb-run --auto-servernum ./gradlew --no-daemon publishJsPublicationToMavenRepository publishAndroidPublicationToMavenRepository -DCI=true
  publish-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install xvfb
      - run: xvfb-run --auto-servernum ./gradlew --no-daemon -DCI=true
      - run: xvfb-run --auto-servernum ./gradlew --no-daemon jvmTest publishLinuxX64PublicationToMavenRepository -DCI=true

  publish-finalize:
    needs: [publish-windows, publish-mac, publish-linux, publish-ios, publish-jvm-multiplatform, publish-js-android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew releaseMavenCentral
