name: "TEST SNAPSHOT"

on:
  schedule:
    # https://crontab.guru/#0_0_*_*_4
    # “At 00:00 on Thursday.”
    - cron: "0 0 * * 4"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Testing JVM and JS
      # https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/kotlin/kotlin-compiler/1.5.255-SNAPSHOT/
      run: FORCED_KOTLIN_VERSION=1.5.255-SNAPSHOT ./gradlew jvmTest jsTest
